UPDATE `{TAB_RESA}` SET date_deb=unix_timestamp(date_deb) WHERE date_deb LIKE "%-%";[END]
UPDATE `{TAB_RESA}` SET date_fin=unix_timestamp(concat(date_fin,' 23:59:59')) WHERE date_fin LIKE "%-%";[END]
ALTER TABLE `{TAB_RESA}` ADD `object` VARCHAR( 255 ) NOT NULL AFTER `periph_id`;[END]
ALTER TABLE `{TAB_SOFT_OCS_ALIAS}` DROP `ocs_soft_version`, DROP `ouapi_soft_version`, DROP `ouapi_soft_date`;[END]
ALTER TABLE `{TAB_SOFT_OCS_ALIAS}` DROP PRIMARY KEY, ADD PRIMARY KEY(`ocs_soft_name`);[END]
ALTER TABLE `{TAB_SOFT_OCS_ALIAS}` ADD UNIQUE (`id`);[END]
ALTER TABLE `{TAB_SOFT_OCS_ALIAS}` CHANGE `id` `id` INT( 11 ) NOT NULL AUTO_INCREMENT;[END]
UPDATE `{TAB_CONFIG}` SET globale="1" WHERE nom LIKE "OCS_%";[END]
ALTER TABLE `{TAB_CONTRAT}` DROP `prolongation_contrat_id`;[END]
ALTER TABLE `{TAB_SOFT}` CHANGE `dern_version_num` `dern_version_num` VARCHAR( 20 ) NULL DEFAULT NULL;[END]
ALTER TABLE `{TAB_SOFT}` DROP `nom_raccourci`;[END]
ALTER TABLE `{TAB_SOFT}` DROP `suivi_maj`;[END]
UPDATE `{TAB_CONFIG}` SET `valeur` = '0.5' WHERE `{TAB_CONFIG}`.`nom` = "gen_version";[END]