UPDATE `{TAB_CONFIG}` SET `valeur` = '1.3' WHERE `{TAB_CONFIG}`.`nom` = 'gen_version';[END]
ALTER TABLE `{TAB_USERS}` ADD `locked` INT( 1 ) NOT NULL DEFAULT '0';[END]
ALTER TABLE `{TAB_USERS_GRP}` ADD `locked` INT( 1 ) NOT NULL DEFAULT '0';[END]
UPDATE `{TAB_USERS}` SET locked = '1' WHERE id = '1';[END]
UPDATE `{TAB_USERS_GRP}` SET locked = '1' WHERE id = '10';[END]
INSERT INTO `{TAB_CONFIG}` (`nom` ,`libelle` ,`description` ,`valeur` ,`form_type` ,`globale`) VALUES ('param_enable_guest', 'Activer le profil Invité', 'Permet d\'utiliser OUAPI sans authentification', '0', 'radio_yn', '1');[END]
INSERT INTO `{TAB_USERS_GRP}` (`id` ,`libelle` ,`locked`) VALUES ('100', 'Invité', '1');[END]
ALTER TABLE `{TAB_USERS_GRP}` ADD `rights` VARCHAR( 255 ) NOT NULL AFTER `libelle`;[END]
ALTER TABLE `{TAB_USERS}` ADD `rights` VARCHAR( 255 ) NOT NULL AFTER `langue`;[END]
UPDATE `{TAB_CONFIG}` SET valeur=id WHERE nom LIKE 'RGHT_%';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Multisite] Accès à tous les sites' WHERE `{TAB_CONFIG}`.`nom` = 'rght_gen_multisite';[END]
DELETE FROM `{TAB_CONFIG}` WHERE `nom` = 'rght_hard_connect';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Matériels] Niv. 1 : Consultation' WHERE `{TAB_CONFIG}`.`nom` = 'rght_hard';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Matériels] Niv. 2 : Edition' WHERE `{TAB_CONFIG}`.`nom` = 'rght_hard_edit';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Matériels] Niv. 3 : Administration' WHERE `{TAB_CONFIG}`.`nom` = 'rght_hard_admin';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Périphériques] Niv. 1 : Consultation' WHERE `{TAB_CONFIG}`.`nom` = 'rght_periph';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Périphériques] Niv. 2 : Edition' WHERE `{TAB_CONFIG}`.`nom` = 'rght_periph_edit';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Périphériques] Niv. 3 : Administration' WHERE `{TAB_CONFIG}`.`nom` = 'rght_periph_admin';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Logiciels] Niv. 1 : Consultation' WHERE `{TAB_CONFIG}`.`nom` = 'rght_soft';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Logiciels] Niv. 2 : Edition' WHERE `{TAB_CONFIG}`.`nom` = 'rght_soft_edit';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Logiciels] Niv. 3 : Administration' WHERE `{TAB_CONFIG}`.`nom` = 'rght_soft_admin';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Utilisateurs] Niv. 1 : Consultation' WHERE `{TAB_CONFIG}`.`nom` = 'rght_users';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Utilisateurs] Niv. 2 : Edition' WHERE `{TAB_CONFIG}`.`nom` = 'rght_users_edit';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Utilisateurs] Niv. 3 : Administration' WHERE `{TAB_CONFIG}`.`nom` = 'rght_users_admin';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Réseau] Niv. 1 : Consultation' WHERE `{TAB_CONFIG}`.`nom` = 'rght_netw';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Réseau] Niv. 2 : Edition' WHERE `{TAB_CONFIG}`.`nom` = 'rght_netw_edit';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Réseau] Niv. 3 : Administration' WHERE `{TAB_CONFIG}`.`nom` = 'rght_netw_admin';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Réservations] Niv. 1 : Consultation' WHERE `{TAB_CONFIG}`.`nom` = 'rght_resa';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Réservations] Niv. 2 : Edition' WHERE `{TAB_CONFIG}`.`nom` = 'rght_resa_edit';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Réservations] Niv. 3 : Administration' WHERE `{TAB_CONFIG}`.`nom` = 'rght_resa_admin';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Documents] Niv. 1 : Consultation' WHERE `{TAB_CONFIG}`.`nom` = 'rght_docs';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Documents] Niv. 2 : Edition' WHERE `{TAB_CONFIG}`.`nom` =  'rght_docs_edit';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Rubrique Documents] Niv. 3 : Administration' WHERE `{TAB_CONFIG}`.`nom` =  'rght_docs_admin';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Outils Administration] Accès total' WHERE `{TAB_CONFIG}`.`nom` = 'rght_admin';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Général] Gestion des tables secondaires' WHERE `{TAB_CONFIG}`.`nom` =  'rght_gen_tableedit';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Mon espace] Consultation' WHERE `{TAB_CONFIG}`.`nom` = 'rght_my';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Moteur de recherche] Accès total' WHERE `{TAB_CONFIG}`.`nom` = 'rght_search';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Module OCS] Niv. 1 : Consultation' WHERE `{TAB_CONFIG}`.`nom` = 'rght_ocs';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Module OCS] Niv. 2 : Edition' WHERE `{TAB_CONFIG}`.`nom` = 'rght_ocs_edit';[END]
UPDATE `{TAB_CONFIG}` SET `libelle` = '[Module OCS] Niv. 3 : Administration' WHERE `{TAB_CONFIG}`.`nom` = 'rght_ocs_admin';[END]
CREATE TABLE `{TAB_USERS_PS}` (`id` INT( 10 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,`user_id` INT( 4 ) NOT NULL ,`category` VARCHAR( 255 ) NOT NULL ,`subcategory` VARCHAR( 255 ) NOT NULL ,`display_settings` TEXT NOT NULL) ENGINE=MyISAM  DEFAULT CHARSET=latin1;[END]
INSERT INTO `{TAB_USERS_PS}` (`user_id` ,`category` ,`display_settings`) VALUES ('0', 'hard', '{DB_PREFIX}hardware.nom;{DB_PREFIX}emplacement.libelle;{DB_PREFIX}utilisateur.nom;{DB_PREFIX}utilisateur.prenom;{DB_PREFIX}ha_marque.libelle;{DB_PREFIX}ha_modele.libelle;{DB_PREFIX}ha_os.libelle;{DB_PREFIX}hardware.num_serie;{DB_PREFIX}hardware.commentaire;{DB_PREFIX}hardware.creation_date');[END]
INSERT INTO `{TAB_USERS_PS}` (`user_id` ,`category` ,`display_settings`) VALUES ('0', 'periph', '{DB_PREFIX}hardware.nom;{DB_PREFIX}peripherique.nom;{DB_PREFIX}ha_marque.libelle;{DB_PREFIX}pe_modele.libelle;{DB_PREFIX}peripherique.num_serie;{DB_PREFIX}peripherique.commentaire;{DB_PREFIX}peripherique.creation_date;');[END]
INSERT INTO `{TAB_USERS_PS}` (`user_id` ,`category` ,`display_settings`) VALUES ('0', 'soft', '{DB_PREFIX}software.nom;{DB_PREFIX}ha_marque.libelle;{DB_PREFIX}software.dern_version_num;{DB_PREFIX}software.dern_version_date;{DB_PREFIX}software.commentaire;');[END]
INSERT INTO `{TAB_USERS_PS}` (`user_id` ,`category` ,`subcategory` ,`display_settings`) VALUES ('0', 'resa', 'hard', '{DB_PREFIX}hardware.nom;{DB_PREFIX}ha_marque.libelle;{DB_PREFIX}ha_modele.libelle;');[END]
INSERT INTO `{TAB_USERS_PS}` (`user_id` ,`category` ,`subcategory` ,`display_settings`) VALUES ('0', 'resa', 'periph', '{DB_PREFIX}hardware.nom;{DB_PREFIX}ha_marque.libelle;{DB_PREFIX}ha_modele.libelle;');[END]
INSERT INTO `{TAB_USERS_PS}` (`user_id`, `category`, `display_settings`) VALUES ('0', 'docs', '{DB_PREFIX}entreprise.raison_sociale;{DB_PREFIX}docs.reference;{DB_PREFIX}docs.date;{DB_PREFIX}docs.commentaire;');[END]
INSERT INTO `{TAB_USERS_PS}` (`user_id`, `category`, `display_settings`) VALUES ('0', 'netw', '{DB_PREFIX}reseau.num_prise;alias_switchname.nom;{DB_PREFIX}reseau.port_id;{DB_PREFIX}hardware.nom;{DB_PREFIX}emplacement.libelle;');[END]
INSERT INTO `{TAB_USERS_PS}` (`user_id`, `category`, `display_settings`) VALUES ('0', 'ldap', 'LDAP_ATTR_LNAME;LDAP_ATTR_FNAME;LDAP_ATTR_MAIL;LDAP_ATTR_LOGINWIN;');[END]
INSERT INTO `{TAB_USERS_PS}` (`user_id`, `category`, `display_settings`) VALUES ('0', 'users', '{DB_PREFIX}utilisateur.nom;{DB_PREFIX}utilisateur.prenom;{DB_PREFIX}utilisateur.mail;{DB_PREFIX}utilisateur.login_win;{DB_PREFIX}ut_groupe.libelle;');[END]
INSERT INTO `{TAB_CONFIG}` (`nom`, `libelle`, `description`, `valeur`, `form_type`, `globale`) VALUES ('rght_ldap', '[Module LDAP] Niv. 1 : Consultation', NULL, 'LDAP1', '', '1');[END]
INSERT INTO `{TAB_CONFIG}` (`nom`, `libelle`, `description`, `valeur`, `form_type`, `globale`) VALUES ('rght_ldap_edit', '[Module LDAP] Niv. 2 : Edition', NULL, 'LDAP2', '', '1');[END]
INSERT INTO `{TAB_CONFIG}` (`nom`, `libelle`, `description`, `valeur`, `form_type`, `globale`) VALUES ('rght_ldap_admin', '[Module LDAP] Niv. 3 : Administration', NULL, 'LDAP3', '', '1');[END]
DELETE FROM `{TAB_CONFIG}` WHERE `nom` = 'db_prefix';[END]
ALTER TABLE `{TAB_SOFT_LICENCE}` CHANGE `serial` `serial` VARCHAR( 255 ) NOT NULL;[END]
ALTER TABLE `{TAB_CONFIG}` ADD `subcategory` VARCHAR( 255 ) NOT NULL AFTER `nom`;[END]
INSERT INTO `{TAB_USERS_PS}` (`user_id` ,`category` ,`subcategory` ,`display_settings`) VALUES ( '0', 'accueil', '', 'MY_PARAMS;MY_ACTIONS;MY_LINKS;MY_TASKS;');[END]
CREATE TABLE `{TAB_USERS_PL}` (`id` INT( 10 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,`user_id` INT( 4 ) NOT NULL ,`link` VARCHAR( 255 ) NOT NULL ,`libelle` VARCHAR( 255 ) NOT NULL ,`image` VARCHAR( 255 ) NOT NULL,`color` VARCHAR( 255 ) NOT NULL ,`target` VARCHAR( 255 ) NOT NULL) ENGINE=MyISAM  DEFAULT CHARSET=latin1;[END]

